### ISSUE TITLE
Missing Mouse Support

### ISSUE THREAD

**Issue by d4l3k** [rpwoodbu/mosh-chrome#100]
I recently switched to Mosh on my Chromebook and I noticed that I can no longer use my mouse with VIM.
http://vim.wikia.com/wiki/Using_the_mouse_for_Vim_in_an_xterm

The previous SSH app "Secure Shell" that I was using supported clicking in the terminal to change the position of the pointer. It was missing dragging support, but at least it had the basics.
https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo

I'm not sure if this is in standard mosh, but I would really appreciate it being supported on ChromeOS. 

Here's the xterm spec:
http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking

**Comment by rpwoodbu** [comment]
Ah, you can help test this, then! Please find and install the "Mosh (dev)" app from the web store, and give it a go. Mouse support was added in the recent upstream Mosh release, which is in the dev channel but not yet released to the stable Mosh for Chrome. It also depends on mouse support in the JS terminal emulator, which is the same one used by Secure Shell, so it should be OK, but more testing is warranted. I don't use this feature, so I'm glad you spoke up.

Let me know how it goes.

**Comment by d4l3k** [comment]
Awesome! Seems to be working just as well as the Secure Shell extension.

It'd be nice if you could click and drag to resize things in VIM, but basic support is much better than nothing.

Thanks for the quick response!

**Comment by rpwoodbu** [comment]
Great to hear! Just so I understand: Does the vim resizing you mention work in other terminals? What about if that terminal connects via mosh 1.2.5 (not in Chrome)? Does it work in Secure Shell? I want to understand if it is an issue with hterm or mosh.

**Comment by d4l3k** [comment]
I know the Vim resizing works with the xfce4-terminal, but other than that I'm not too sure. Secure shell doesn't support resizing, just changing the cursor location (like Mosh (dev) does now).

I did notice a bug with Mosh (Dev) with mouse input where in vim it would insert gibberish characters instead of moving the cursor. I'd give exact reproduction steps but I'm now getting a different error with Mosh (Dev).
```
Loading NaCl module (takes a while the first time after an update).
[...............]
Loaded.
Could not connect via ssh: ed25519 signature verification error

SSH Login failed.

Mosh has exited.
Press "x" to close the window.
```
Normal Mosh works just fine.

**Comment by rpwoodbu** [comment]
Uh oh, you're now the second person to report this ed25519 thing. Moving that conversation to Issue #102.

If the vim resizing works in xfce4-terminal while using the command-line mosh, then it sounds like the issue is hterm. That satisfies my curiosity. If you're anxious to get this feature, see if you can convince the hterm/nassh folks to add it. It will then make it into Mosh for Chrome as part of an hterm upgrade.
