### ISSUE TITLE
Can we make Mosh for Chrome completely full screen (i.e. hide everything else)

### ISSUE THREAD

**Issue by computersarecool** [rpwoodbu/mosh-chrome#104]
I must say, this is an incredible app and I love it very much.

I am wondering if it would be possible to make this takeover my entire screen so that I do not see any of the system tray or menu bars.

I found [this link] (http://stackoverflow.com/questions/15451888/how-can-i-make-a-chrome-packaged-app-which-runs-in-fullscreen-at-startup) which makes it sounds not very difficult, but I just wasn't sure if there was some limitation about which I did not know.

Please let me know thoughts on this, and, again, thanks for all of your work on this.

**Comment by rpwoodbu** [comment]
Usually there's a platform-specific way to make any app run full-screen. On Chrome OS, there's a full screen button (where F4 would be), and it works with Mosh for Chrome. I'd expect other platforms to have similar facilities IIRC, F11 is popular for this in Linux. My distant memory is that Windows likes Alt-Enter, but maybe that was just for video games. :) I think I learned once that the Mac has something involving pressing a lot of buttons and then F. Let me know if you figure it out on your platform.
