### ISSUE TITLE
SSH-Key still asking for password once removed?

### ISSUE THREAD

**Issue by computersarecool** [rpwoodbu/mosh-chrome#105]
I recently ran 

`ssh-keygen -p [-P old_passphrase] [-N new_passphrase] [-f keyfile]` to remove the passphrase from my ssh key.  I then removed the key from Mosh Chrome, uninstalled Mosh Chrome and then reinstalled mosh Chome.

Upon logging into my server again, I am still asked for the passphrase for my ssh key each time.  Entering in the old passphrase logs me in.

I am not asked for a passphrase when using mosh from the OS X terminal.  Any solutions here?

**Comment by rpwoodbu** [comment]
If what you said is precise and accurate, then Mosh for Chrome should not have your ssh key at all anymore, as you removed it without putting one back. Are you sure it isn't asking for your ssh login password?

**Comment by computersarecool** [comment]
It was indeed, I am sorry for the false alarm.
