### ISSUE TITLE
Scroll preference setting

### ISSUE THREAD

**Issue by ruthlesssinner** [rpwoodbu/mosh-chrome#108]
Wonderful app. Just what was needed on Windows.
Scroll back seems to be disabled and I cant find the preference setting for enabling it as well as the number of lines to store.

**Comment by rpwoodbu** [comment]
Mosh doesn't currently have scrollback support. Please see the [mosh FAQ](https://mosh.mit.edu/#faq) and search the page for "scrollback". tl;dr: Use mosh with tmux or screen to get scrollback capability.
