### ISSUE TITLE
Mosh client hangs on loading NaCl module

### ISSUE THREAD

**Issue by sasnfbi1234** [rpwoodbu/mosh-chrome#110]
I am on Ubuntu running chrome 45.

it just sits there

**Comment by keithw** [comment]
Are we talking `chromium-browser` here, or Google Chrome from Google. My understanding is that Ubuntu's `chromium-browser` just doesn't have NaCl.

**Comment by rpwoodbu** [comment]
Oh, if that's true, I should do something to detect that and display a useful message.

**Comment by rpwoodbu** [comment]
I haven't heard of this since, so I'm going to close. Please update if there's more information to bring to bear.
