### ISSUE TITLE
Cannot Load External Stylesheets When Running on ChromeOS

### ISSUE THREAD

**Issue by necopinus** [rpwoodbu/mosh-chrome#113]
Trying to set an external stylesheet via the `user-css` preference doesn't work. For example, attempting to use the "Hack" font results in:
```
Refused to load the stylesheet 'https://cdn.jsdelivr.net/font-hack/2.018/css/hack-extended.min.css' because it violates the following Content Security Policy directive: "style-src 'self' blob: filesystem: data: chrome-extension-resource: 'unsafe-inline'".
hterm.ScrollPort.setUserCss @ hterm.js:3661
```
Interestingly, this issue is _only_ present under Chrome OS for me -- using the same stylesheet but via Chrome on Mac OS X works fine.

Setting the style sheet works on Chrome Secure Shell under both Mac OS X _and_ Chrome OS.

FWIW, I'm pretty sure this is the same issue as reported in [#51](https://github.com/rpwoodbu/mosh-chrome/issues/51). But the symptoms seem _slightly_ different, which is why I'm opening it up as a separate ticket. The difference in behavior between the app under Chrome OS and the app run through Chrome on other operating systems seems a potentially useful data-point.

**Comment by wiz** [comment]
Is there a possible fix?

**Comment by rpwoodbu** [comment]
Sorry, folks, I've been stupid busy and haven't been able to give Mosh for Chrome much attention. My initial guess is that this isn't allowed for Packaged Apps (as per #51, which @necopinus pointed out). Secure Shell is not a Packaged App. Mosh for Chrome must be to get access to the APIs necessary to do UDP (or at least that was the case when I started the project; I haven't looked to see if anything has changed there).

If it works on Mac OS X but not on Chrome OS, that sounds like a Chrome bug and should be reported. So for now I'm going to call this a dup of #51.

**Comment by wiz** [comment]
Take a look https://developer.chrome.com/extensions/contentSecurityPolicy

You can allow `https:` for styles and fonts, maybe images...
