### ISSUE TITLE
Make the "zoom != 100%" hideable

### ISSUE THREAD

**Issue by colemickens** [rpwoodbu/mosh-chrome#118]
This appears even when the resolution is set to a non-native resolution, meaning that it's basically a useless nuisance warning for those of us on Chromebook Pixels.

Further, I crafted some user css that hides the warning when it's inserted with Developer Tools, but it has zero effect when applied via the mosh preferences.

**Comment by rpwoodbu** [comment]
Under what circumstances does this show? I use Ctrl-{Minus,Equals,Zero} to alter the "zoom" all the time, but never see what you're talking about. I am using a Chromebook Pixel in a non-native resolution. I even tried changing the default page zoom setting, but still aren't seeing what you're talking about.

**Comment by colemickens** [comment]
I can't seem to get the Ctrl+{minus,equal,zero} to ever do anything when mosh has focus. It seems to intercept those keys because they never get to the browser.

All I know is... when I hit Ctrl+Shift+minus a few times, my display is set to 0-scaling, and displays at the full native resolution. This is the *only* way I have made the warning go away.

I feel that I'm doing it wrong, but I have no idea what I should be trying instead. Thanks for the help!

**Comment by rpwoodbu** [comment]
Hmm, this is very strange. This is not at all like my experience. Mosh for Chrome uses the same terminal emulator, hterm, as the Secure Shell app. You might try reproducing your experience with that app. If it is the same, you know that it isn't Mosh-specific. If it is different, well, that'll be interesting indeed. Can you also check what version of the app you have installed? At this point it should be 0.3.0.258. If it isn't, maybe there's something in your Chrome OS setup that is preventing apps from getting updates.

There is a settings option called ctrl-plus-minus-zero-zoom, which should be enabled by default. Maybe that's not enabled for you, and at least is what is preventing these keys from working for you. This may also suggest that you have some other configuration items that are causing issues for you. If simply fixing that setting doesn't fully solve your problem, you might try uninstalling and reinstalling the app. However, I'm not sure that'll clear these settings, and they are synchronized... let me know and I can dig up a JS console command you can run to clear that stuff out.

**Comment by colemickens** [comment]
I just installed the app a few days ago. Mosh (dev) 0.2.12.257 and Mosh 0.3.0.258 both display this behavior.

Secure Shell also displays the same behavior, except that with Secure Shell, I can ctrl+{plus,minus}. But, I have to set the page zoom to ~50% (which offsets the display scaling and makes it the tiny native resolution effectively) to get that warning to go away.

Again, with Mosh, I can't figure out any way to get ctrl+{plus,minus} to work, even though that option is enabled and I "Reset to Defaults" from the mosh preferences page.

**Comment by colemickens** [comment]
```
Version 50.0.2661.20 dev (64-bit)
Platform 7978.10.0 (Official Build) dev-channel samus
Firmware Google_Samus.6300.174.0
```

**Comment by rpwoodbu** [comment]
Ah, you're running the dev channel of Chrome OS. Interesting. I have a machine setup with that, so I'll test there. But I'm away on business and won't have a chance to check it out until this coming weekend at the earliest. Hang in there!

**Comment by colemickens** [comment]
Just updated and this has gone away now.
