### ISSUE TITLE
Blurry text in mosh terminal

### ISSUE THREAD

**Issue by mdlui** [rpwoodbu/mosh-chrome#123]
I'm on Windows 10, Chrome 51.0.2704.106. 

Relevant mosh preferences
```
{
font-family: "Fira Code", "DejaVu Sans Mono", "Everson Mono", FreeMono, "Menlo", "Terminal", monospace
font-size: 13
font-smoothing: antialiased
}
```
On the mosh terminal, text is much blurrier than in a normal text area. 

**I attached an example, with a jsfiddle example on top, and mosh on the bottom**. JSfiddle font style options were the same as for the mosh terminal, afaik.
```
{
color: #FFFFFF 
background-color: #000000
font-family: "Fira Code", "DejaVu Sans Mono", "Everson Mono", FreeMono, "Menlo", "Terminal", monospace
font-size: 13
-webkit-font-smoothing: antialiased
}
```

![mosh_hterm_blurry](https://cloud.githubusercontent.com/assets/9659800/16913631/d4ba2bf2-4cb9-11e6-8422-6fbe3df947cc.png)

**Comment by rpwoodbu** [comment]
Do you mind taking the time to repro this in [Secure Shell](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo)? If it happens there, too, then the issue is likely with hterm, the JS terminal emulator that both projects use.

**Comment by mdlui** [comment]
It does happen in Secure Shell as well. Makes sense that it's a hterm problem. After an uncomfortable amount of time looking into fonts, I was able to get around it temporarily by disabling directwrite in chrome://flags, however they've removed that feature in the current stable chrome, and for the foreseeable future. It's going to be an issue as long as the chrome team accepts directwrite as the de-facto font rendering API.
