### ISSUE TITLE
On Ubuntu, how can I see the normal "Welcome Screen"

### ISSUE THREAD

**Issue by computersarecool** [rpwoodbu/mosh-chrome#128]
When I log into my Ubuntu server using something like Putty, I see the normal "Welcome to Ubuntu" screen which shows things like system usage, processes and a general welcome message.

When I log in via Mosh, I do not see this.  

I actually like seeing this welcome message and I am wondering if there is a way I can show it.

To complicate this question, my `.bashrc` file opens an instance of TMUX so to actually see the welcome message (in Putty or anywhere else, I have to momentarily detach from the TMUX session, then connect after viewing the message.  Still, when I do this in Mosh, the message is not there).

**Comment by rpwoodbu** [comment]
This is a server-side issue. Mosh for Chrome starts mosh-server in the same manner as the `mosh` script that comes with the standard upstream package. I suggest testing this by using the `mosh` CLI on Ubuntu to connect to localhost. If it behaves as you describe (and I believe it will), I suggest taking this up with the main Mosh project. (It'd be a good question for their mailing list.)
