### ISSUE TITLE
Windows monospaced fonts don't align properly

### ISSUE THREAD

**Issue by colemickens** [rpwoodbu/mosh-chrome#132]
This only affects me on Windows, where mosh for Chrome is still the best experience for moshing into my servers, despite "bash on Windows" due to hterm working better than conhost.exe.

This seems to be an issue regardless of the font. Here's three different fonts: http://imgur.com/a/GyCq3

You can see, depending on the font, there's either one big glitch, or one big glitch with some smaller ones interspersed as well.

The 'x' characters and the directory '>' arrows seem to not be rendered in the proper width. Not really sure what's at play here, especially since it only happens on Windows.

**Comment by colemickens** [comment]
Looks like this is not Mosh specific: http://i.imgur.com/ZiuNEVn.png

I still don't really know where to dig into this, so if you have any suggestions, it'd be great. Thanks!

**Comment by colemickens** [comment]
Native win32 and UWP are also affected, so this is clearly not a mosh issue: http://i.imgur.com/W4ht1s8.png

Feel free to close this unless anyone has any suggested workarounds. I'll close it soon if I don't hear anything.

**Comment by rpwoodbu** [comment]
This is almost certainly due to an unusual character being displayed that is wider than the normal set of what might be called "ASCII characters". I see a weird character inside the brackets on the left which is causing the issue. Alignment is a common problem for fixed-width situations displaying things like graphics and CJK characters.

**Comment by colemickens** [comment]
Yup, only an issue on Windows. Thanks for closing, I'll try to find someone in Windows to chase this down or find a workaround.

**Comment by bitcrazed** [comment]
@colemickens Hey Cole. Looks like the alignment issue is caused by the star symbol being wider than a single character cell:

![image](https://cloud.githubusercontent.com/assets/961950/18604786/08c72de0-7c36-11e6-9259-e0b727bca66e.png)
