### ISSUE TITLE
Mosh title bar is not updated

### ISSUE THREAD

**Issue by peterjeremy** [rpwoodbu/mosh-chrome#134]
On Unix, the xterm title bar can be set using OSC 2 ; text BEL and mosh intercepts this and appends [mosh].  This doesn't work in Chrome using either 0.3.0.258 or or 0.4.0.

I believe there are some oddities with getting this working because it doesn't work on the first SecureShell session but does work on subsequent SecureShell sessions.

**Comment by rpwoodbu** [comment]
This has always worked fine for me. I just tested on the latest stable Chrome (54.0.2840.41 beta (64-bit)) on Ubuntu Linux (even worked on first session), both Mosh for Chrome 0.3.0.256 and 0.4.0, and I even tested both OSC 0 (which I use) and OSC 2 (which you suggest), and both work fine. Is there something different about your setup?

BTW, this also kind of works on Chrome OS, but as the title bar is blank (there's no way to set title bar text unless you implement all your own window chrome, which I never bothered with), the only place you see it is when you 1) have more than one session going, and 2) click on the app icon in the shelf and see the list of sessions. (As a further aside, I ran across something that suggests there's a new way in Chrome 55 to have separate panel icons for separate windows of your app; I may look into that.)

All that said, I must point you to the hterm component of the Secure Shell project, as they own that code and I just use it. You'll need to bring it up with them. If they provide a fix, please reopen this bug and let me know, so I can rebuild with the latest hterm.

**Comment by rpwoodbu** [comment]
Oh, one more thing: If you're running tmux or screen, you may have some interference there.
