### ISSUE TITLE
Mosh hangs at "Loading NaCl module", Chrome 54.0.2840.71 m (64-bit) on Windows 10

### ISSUE THREAD

**Issue by PenelopeFudd** [rpwoodbu/mosh-chrome#136]
This would be a clone of #94, but Chrome is up to date, and the computer was freshly set up just this week.  After posting this, I see that #124 is even more similar; how do I get a stack trace?

Mosh was working fine, some Windows updates rolled in, and now mosh is hanging.  I don't want to go back to Putty!

**Comment by PenelopeFudd** [comment]
Just tried the developer track version, and after entering username and host, clicking 'Connect', it pops up a black window that does nothing.

**Comment by Z6543** [comment]
I have the same issue.
Chrome Version 54.0.2840.87 m (64-bit)
Windows 10 with latest updates
Mosh  0.3.0.258

**Comment by rpwoodbu** [comment]
This is peculiar. @PenelopeFudd are you running the same version of Chrome as @Z6543? I have another report of someone running with the same versions as @Z6543 without trouble.

You might bring up the JavaScript console for mosh_window.html and see if there are any hints in the log.

**Comment by Z6543** [comment]
This is the content of the JS console:

`init: hterm
mosh_window.js:242 Uncaught TypeError: this.moshNaCl_.postMessage is not a function(…)
mosh_window.js:242 Uncaught TypeError: this.moshNaCl_.postMessage is not a function(…)
mosh_window.html:1 Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at Object.lib.encodeUTF8 (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm_deps.js:4388:26)
    at hterm.Terminal.IO.print.hterm.Terminal.IO.writeUTF16 (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm.js:7787:22)
    at Object.callback (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/mosh_window.js:120:30)
    at mosh.CommandInstance.run (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/mosh_window.js:118:23)
    at hterm.Terminal.runCommandClass (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm.js:5256:16)
    at hterm.Terminal.terminal.onTerminalReady (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/mosh_window.js:40:14)
    at hterm.Terminal.<anonymous> (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm.js:4762:37)
    at hterm.Terminal.<anonymous> (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm.js:5135:7)`

**Comment by rpwoodbu** [comment]
Doesn't seem like there's anything useful on the console (those are all errors from known but innocuous issues). Weird that this isn't happening for everyone.

I have a dev release of a "native" Windows app. Please give that a try and let me know if it works OK. I'll place both links here, but you'll want the x64 one:

https://storage.googleapis.com/mosh-chrome/mosh_for_windows_0.3.7-dev_x64.msi
https://storage.googleapis.com/mosh-chrome/mosh_for_windows_0.3.7-dev_ia32.msi

If that works fine, then I probably won't bother to try to fix this in the app on the Chrome Web Store, as Chrome support for Packaged Apps is going away on Windows et al. soon.

**Comment by Z6543** [comment]
Good news is that it started to work again some days ago, for no reason ...

**Comment by rpwoodbu** [comment]
@Z6543 Was there an update either to Windows or Chrome in that period? How strange.

@PenelopeFudd Is it working for you at this time?

I'm going to go ahead and close this, since it kinda fixed itself, doesn't seem to be widespread, and for the reasons I mentioned earlier. But please do answer the above question FTR.

**Comment by MRGEffitas** [comment]
I have checked the Windows logs, there was no Windows update since. 
Chrome version did not change.
Mosh version did not change.

I think the only change in the system was a Windows restart. Odd ...
Anyway, thanks for looking into this.

**Comment by Z6543** [comment]
The previous post was done by me, from a wrong account :)

**Comment by PenelopeFudd** [comment]
The development version linked above (x64) is working, but the version from the chrome app store is not.  Chrome version Version 54.0.2840.99 m (64-bit) (Windows 10, patched as of today).

Also, I can't start a second session using the dev version; right-clicking on the taskbar icon and selecting 'Mosh' does nothing.

**Comment by PenelopeFudd** [comment]
I've uninstalled and reinstalled Chrome (v51.0.2704.106 m -- not the latest version), and then installed the dev version of Mosh from the Chrome web store (v0.4.4), and it works fine.  Going to try updating Chrome to see if it breaks Mosh.

**Comment by PenelopeFudd** [comment]
Updated version of Chrome works fine with dev and non-dev versions of Mosh from Chrome web store.  Can no longer reproduce the problem.

**Comment by PenelopeFudd** [comment]
I'm sorry, but mosh broke again.

Chrome versions tested: 
 Version 55.0.2883.75 m (64-bit) --- before update
 Version 55.0.2883.87 m (64-bit) --- after update; current version as of 2016-12-14

Mosh-chrome versions tested:
  v0.3.0.258  -- from chrome webstore
  v0.4.4  -- dev stream from chrome webstore

The non-dev version asks for connection information, then opens the terminal window, says "Loading NaCl module (takes a while the first time after an update).  [............]" and hangs.

The dev version asks for connection information, opens the terminal window, and prints nothing.

Trying the msi version linked above now.

**Comment by PenelopeFudd** [comment]
Ok, this worked: https://storage.googleapis.com/mosh-chrome/mosh_for_windows_0.3.7-dev_x64.msi

**Comment by PenelopeFudd** [comment]
Sigh.  It works except for the fact that I can only open one mosh session at a time.  If I want two terminal windows, I have to use putty.

**Comment by rpwoodbu** [comment]
Not sure what the deal is with your Chrome installation refusing to run Mosh sometimes. Here's the reality, though: If it isn't broken on Chrome OS, or in the "native" app, then it isn't getting fixed. This is because Google has decided to eliminate support for Chrome Apps in the near future on all platforms but Chrome OS.

That said, the "only one session at a time" problem exists in the "native" app. As you know, Issue #137 is tracking that.
