### ISSUE TITLE
Mosh 0.3.0.258 hangs at "Loading NaCl module", Chrome Version 55.0.2883.87 m (64-bit) on Windows 10 

### ISSUE THREAD

**Issue by PenelopeFudd** [rpwoodbu/mosh-chrome#139]
Creating a new issue as I don't have the power to reopen #136.

Mosh 0.3.0.258 + Chrome Version 55.0.2883.87 m (64-bit) + Windows 10: Hang at 'Loading NaCl module'
Mosh 0.4.4 + Chrome Version 55.0.2883.87 m (64-bit) + Windows 10: Hang with blank terminal window
Mosh native app 0.3.7 + Windows 10: Works, but can't open a second window (See #137 )

Right-clicking on the Mosh native app on the taskbar brings up a menu, but clicking on the 'Mosh' entry on that menu does nothing, whereas it should have started another copy of Mosh, if I understand things correctly.

**Comment by rpwoodbu** [comment]
Please see the original Issue #139.
