### ISSUE TITLE
Powerline fonts not working in mosh?

### ISSUE THREAD

**Issue by tlnagy** [rpwoodbu/mosh-chrome#145]
I'm on OS X and playing around with mosh. I was hoping that powerline fonts would work. I'm using https://github.com/wernight/powerline-web-fonts, which works great with chrome secure shell, but doesn't seem to work when I set it up the same way in mosh:

![image](https://cloud.githubusercontent.com/assets/1661487/23829315/2aeceb3c-06a4-11e7-9132-d9468736640c.png)

**Comment by rpwoodbu** [comment]
I just updated the dev channel to hterm 1.61. I was a few versions behind, so maybe an issue in hterm had been fixed in the interim. (hterm is the same terminal emulator used by both Mosh for Chrome and Secure Shell.)

Please install "Mosh (dev)" if you'd like to test this out sooner than later.

**Comment by tlnagy** [comment]
It looks like mosh-dev still has this problem:

![image](https://cloud.githubusercontent.com/assets/1661487/24419999/178e5ee0-13a6-11e7-9f7e-12ce040e1ad4.png)

**Comment by rpwoodbu** [comment]
Hmm, OK. I wonder if there are any permissions issues with getting at those web fonts. When I get time, I'll try it out locally. Before then, though, if you can check the JS console for the terminal window to see if there are any unusual messages, that would be helpful.

**Comment by tlnagy** [comment]
How do I bring up the JS console? I'm not sure how to activate it for chrome extensions.

**Comment by dustinosity** [comment]
I'm having the same issue in chrome OS on a chromebook. In my js console I'm getting:
`Refused to load the stylesheet 'https://cdn.rawgit.com/wernight/powerline-web-fonts/8040cf32c146c7cd4f776c1484d23dc40685c1bc/PowerlineFonts.css' because it violates the following Content Security Policy directive: "style-src 'self' blob: filesystem: data: chrome-extension-resource: 'unsafe-inline'".`

**Comment by dustinosity** [comment]
@tlnagy here's how to bring up the JS console according the the mosh-chrome FAQ:

> (If you need to open the Javascript console: "Go to `chrome://extensions` and click `Developer mode`. Then find Mosh on the page, and while Mosh is running and connected, click `mosh_window.html`. That will pop up the developer tools; there click `Console`.)"

via https://github.com/rpwoodbu/mosh-chrome/wiki/FAQ#how-can-i-change-the-way-the-terminal-looks-font-color-etc

**Comment by tlnagy** [comment]
Thanks @dustinosity, I see the exact same thing:

```js
Refused to load the stylesheet 'https://cdn.rawgit.com/wernight/powerline-web-fonts/8040cf32c146c7cd4f776c1484d23dc40685c1bc/PowerlineFonts.css' because it violates the following Content Security Policy directive: "style-src 'self' blob: filesystem: data: chrome-extension-resource: 'unsafe-inline'".
```

**Comment by NHDaly** [comment]
Could this possibly be an issue with [wernight/powerline-web-fonts](https://github.com/wernight/powerline-web-fonts), rather than with mosh? Is there some security promise that the fonts needs to make? I'll start an issue there as well to ask.

**Comment by rpwoodbu** [comment]
This is a dup of Issue #121. Let's move the discussion there.
