### ISSUE TITLE
Ctrl-Click on highlighted URL not functioning

### ISSUE THREAD

**Issue by thatfunkymunki** [rpwoodbu/mosh-chrome#150]
HTerm 1.61 https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/doc/ChangeLog.md added a feature where if you have a URL highlighted, when you ctrl-click it, it will open it in a new tab in your browser. This is currently functioning in Secure Shell but not mosh-chrome

**Comment by thatfunkymunki** [comment]
the relevant change that was merged into hterm can be found here https://chromium-review.googlesource.com/c/433392 and here https://chromium-review.googlesource.com/c/433392/2/hterm/js/hterm_terminal.js

**Comment by rpwoodbu** [comment]
Dup of #143.

I haven't released a new Mosh for Chrome with this yet, but the dev track "Mosh (dev)" has it if you're anxious​.

**Comment by thatfunkymunki** [comment]
Sorry about that! Thought I searched well enough...
