### ISSUE TITLE
The terminal remains black if username is not provided

### ISSUE THREAD

**Issue by rayluo** [rpwoodbu/mosh-chrome#152]
How to reproduce: In the first UI of Mosh-chrome, leave the username input empty [1], and setup every other fields correctly. Now hit the "Connect" button, you will see a blank black terminal window but no connection is made.

Suggested fix: the UI should detect such input error and give an error message saying "username is a mandatory field".

[1] Yeah, normally the username field are not expected to be empty, but sometimes user may think he/she can use an empty input to represent the default username. Mosh-chrome does NOT have to support the default username feature, just an explicit input-error prompt would be sufficient.

**Comment by rpwoodbu** [comment]
Good catch. I can repro.

**Comment by rpwoodbu** [comment]
The error message now actually shows properly, which fixes this bug. However, I could rather easily add an interactive prompt for the username just as I do for the password if it isn't provided in the web field; is that something worth doing?

**Comment by rpwoodbu** [comment]
(BTW, this is going out to "Mosh (dev)" as I type this.)

**Comment by rayluo** [comment]
Thanks for quick response! Yes I can see the error prompt in Mosh (Dev) now.

The interactive prompt you suggested is a completely different topic. It can be useful in a scenario when user have multiple accounts using username/password login, and then choosing accounts on the fly. For other scenario using ssh-key login, Mosh Chrome provides no way to easily switch key anyway, so prompting username on the fly is irrelevant.
