### ISSUE TITLE
Failure to examine libssh2_userauth_authenticated leads to failure to use "none" authentication.

### ISSUE THREAD

**Issue by MakeItGreatAgain** [rpwoodbu/mosh-chrome#156]
per the libssh2 docs: https://www.libssh2.org/libssh2_userauth_list.html:
> "Send a SSH_USERAUTH_NONE request to the remote host. Unless the remote host is configured to accept none as a viable authentication scheme (unlikely), it will return SSH_USERAUTH_FAILURE along with a listing of what authentication schemes it does support. In the unlikely event that none authentication succeeds, this method with return NULL. This case may be distinguished from a failing case by examining libssh2_userauth_authenticated."

The chrome-mosh code never does this check, thus "none" authentication is broken.  This can be confirmed by attempting to connect to my public Multics host (`mosh dps8@m.trnsz.com`):

`Authentication types supported by server:`
`Failed to get authentication types: `

This will succeed as expected in Prompt, Reflection, PuTTY, and OpenSSH, but fails in mosh-chrome and blinksh mosh/ssh due to the same bug of never checking libssh2_userauth_authenticated.

**Comment by MakeItGreatAgain** [comment]
Note: Edited original issue to include test case of mosh dps8@m.trnsz.com

**Comment by rpwoodbu** [comment]
Well, Mosh for Chrome uses libssh, not libssh2. However, it too exhibits similar behavior, with slightly different semantics. I even acknowledge that this doesn't work right in a comment [here](https://github.com/rpwoodbu/mosh-chrome/blob/master/mosh_nacl/ssh.cc#L139).

This shouldn't be terribly hard to fix. I think ssh::Session::GetAuthenticationTypes() could just return SSH_AUTH_METHOD_NONE (which would need to be added as kNone to ssh::AuthenticationTypes (and this would be a good opportunity to switch to a scoped enum), and handled in a few places like ssh::GetAuthenticationTypeName()) when it gets back SSH_AUTH_SUCCESS from ssh_userauth_none(), then handle that in SSHLogin::Start().
