### ISSUE TITLE
Server fingerprint will not store.

### ISSUE THREAD

**Issue by MyBrokenPC** [rpwoodbu/mosh-chrome#159]
for some reason this will not store the MD5 finger print. 

Could NOT authenticate DNS lookup.
Unauthenticated SSHFP fingerprint record(s) in DNS; ignoring.
Remote ssh host name/address:
  65.XX.XX.XX:22
ssh-rsa key fingerprint of remote ssh host (MD5):
  be:58:a3:32:78:31:91:1e:7e:eb:42:0b:04:38:36:ed
Server fingerprint unknown. Store and continue? (Yes/No): y
Please specify Yes or No.
Server fingerprint unknown. Store and continue? (Yes/No): y
Please specify Yes or No.
Server fingerprint unknown. Store and continue? (Yes/No): y
Please specify Yes or No.
SSH Login failed.

Mosh has exited.
Press "x" to close the window.

**Comment by rpwoodbu** [comment]
You must specify "Yes or No", not "y".

**Comment by rpwoodbu** [comment]
Also, consider getting DNSSEC going and turning on DNS-over-HTTPS, so you don't _have_ to store the fingerprints. 😉
