### ISSUE TITLE
How to save password?

### ISSUE THREAD

**Issue by uroot** [rpwoodbu/mosh-chrome#162]
I must to input ssh password everytimes ,how can I save it in mosh?

**Comment by rpwoodbu** [comment]
It is rare for any ssh program to save passwords, and Mosh for Chrome is no exception. The preferred method is to setup a public key (which itself can have a passphrase). Please see the [FAQ entry](https://github.com/rpwoodbu/mosh-chrome/wiki/Key-based-ssh-Authentication) for how to configure this in Mosh for Chrome. If you need help setting up public key authentication in ssh, you will find numerous guides online; I recommend getting it working with regular ssh before using it with Mosh for Chrome.
