### ISSUE TITLE
Character width issues

### ISSUE THREAD

**Issue by cccCody** [rpwoodbu/mosh-chrome#163]
Something weird is going on with character width here. I'm running tmux (latest from master), zsh 5.0.7, zprezto, and powerlevel9k. I'm using a font from [nerd-fonts](https://github.com/ryanoasis/nerd-fonts), but it happens with the default font too

![tmux](https://user-images.githubusercontent.com/753031/32390083-38e3f9f6-c08a-11e7-95f5-f085fec539f4.png)

**Comment by rpwoodbu** [comment]
Might this be a dup of #163?

**Comment by cccCody** [comment]
I can repro that cursor issue with some specific fonts, mostly from the nerd-fonts package I linked to above. But I can repro this issue using fonts that don't have the issue in #148. Seems likely that these issues are at least related, but not necessarily a dupe.

**Comment by rpwoodbu** [comment]
OK. Could you try reproducing this with the Secure Shell app? These problems are always related to hterm, which is the terminal emulator used by both apps. If this repros there, you'll need to bring it up with them (as they maintain hterm). If it doesn't, then maybe it has been fixed, and it is time to try a newer hterm.

**Comment by cccCody** [comment]
Yup, it happens in secure shell too. I'll look into reporting this to them.

**Comment by rpwoodbu** [comment]
OK. If/when it gets fixed in hterm, ping this issue and I'll see about picking up that fix.
