### ISSUE TITLE
Unable to login when 2fa is enabled

### ISSUE THREAD

**Issue by jessesung** [rpwoodbu/mosh-chrome#169]
If OTP or password is added as a second factor besides publickey, mosh will not be able to login. The Secure Shell extension itself works though.

Openssh client with -vvv shows:
`debug1: Authentications that can continue: publickey`
...
`Authenticated with partial success.`
`debug1: Authentications that can continue: keyboard-interactive`
`debug3: start over, passed a different list keyboard-interactive`
...
`Verification code:`

And mosh-chrome shows:
`Authentication types supported by server:`
` - Public Key`
`Trying authentication type Public Key`
`Passphrase:`
`Key auth failed: Access denied. Authentication that can continue: publickey`
`ssh authentication failed: Access denied. Authentication that can continue: publickey`
`SSH Login failed.`
`Mosh has exited.`

**Comment by rpwoodbu** [comment]
I don't believe this is a problem with 2FA. I went to some effort to make this work a while back. I have just tested this again, and it works for me.

Based on the text you pasted, it seems like there's something amiss with the public/private key configuration on one end or the other. Try reconfiguring your key in Mosh for Chrome and verifying the `authorized_keys` file on your server.

I'm going to go ahead and close this, but please let me know if you still have trouble, and have any other data to bring to bear.

**Comment by jessesung** [comment]
@rpwoodbu: Thanks for your reply.

I tried to disable 2fa after I got your reply, mosh-chrome logged in without any problem. Then I enabled 2fa, and got the same error messages again. So likely it's not a key issue.

I'm wondering if there's any way I can get more debug message for you?

**Comment by Strykar** [comment]
@jessesung Is your SSH 2FA using PAM? If not, it won't work, see https://github.com/mobile-shell/mosh/issues/506

**Comment by jessesung** [comment]
@Strykar Yes, it is using PAM.
