### ISSUE TITLE
Chrome apps are being deprecated

### ISSUE THREAD

**Issue by magical** [rpwoodbu/mosh-chrome#171]
- Google [recently removed][1] the ability to install Apps on any platform except Chrome OS, and even Chrome OS support seems destined to be removed

- Given that mosh-chrome is the [recommended][2] way to use mosh on Windows, is there any migration plan? 

[1]: https://arstechnica.com/gadgets/2017/12/google-shuts-down-the-apps-section-of-the-chrome-web-store/
[2]: https://mosh.org/#getting

**Comment by eminence** [comment]
mosh on [msys2](http://www.msys2.org) is a very pleasant experience, so this could be a good migration plan for people who don't mine installing and keeping msys2 up-to-date.

**Comment by rpwoodbu** [comment]
There is a Windows version in beta as of [release 0.4.5](https://github.com/rpwoodbu/mosh-chrome/releases/tag/v0.4.5).

**Comment by magical** [comment]
Ah, i missed that. Thanks.
