### ISSUE TITLE
Please verify that UDP port 60002 is not firewalled and can reach the server.

### ISSUE THREAD

**Issue by Stockton-pr** [rpwoodbu/mosh-chrome#178]
I am successfully connecting to a DO droplet with secure shell on an Acer 14 cb beta channel, but using mosh the top bar tells me that it cannot connect on port 6001, then when i try again same for  6002. Presumably this is not an ssh key pair issue as the same keys are in use on the secure shell set up. AFAIAA there is no firewall on the DO droplet (ubuntu 16). any advice very welcome! Sorry i am a bit knew to this noob alert!

**Comment by Stockton-pr** [comment]
My bad the droplet welcome screen says:
The UFW firewall is enabled. All ports execpt for SSH anby default.
solved by sudo ufw allow 60000:61000/udp

Sorry for any bother:admin please close!

**Comment by rpwoodbu** [comment]
Glad you figured it out.
