### ISSUE TITLE
Maximizing window on Windows 10 Pro 4k monitor loses leftmost pixels

### ISSUE THREAD

**Issue by ryantm** [rpwoodbu/mosh-chrome#189]
When I maximize the mosh-chrome version v0.4.6 (mosh 1.2.6) app on Windows 10 Pro (1803 OS build 17134.48) computer the leftmost pixels are cut off. Here is a screencapture of it:

![image](https://user-images.githubusercontent.com/4804/42395944-817755dc-8114-11e8-9464-afff56f350f0.png)

My monitor resolution is 2160x3840. My "Scale and layout" size is "150% (Recommended)". If I set the "Scale and Layout" to "100%". It does not cut off the pixels.

**Comment by rpwoodbu** [comment]
Try this with the "Mosh (dev)" from the Chrome Web Store. It has a newer version of the terminal emulator, which may solve the issue. I will be pushing an even newer one tonight (v0.5.5).

**Comment by ryantm** [comment]
Thank you for replying. I forgot to mention that I did try it with "Mosh (dev)" back when I originally posted and it had the same problem. I will try v0.5.5 tomorrow.

**Comment by ryantm** [comment]
@rpwoodbu  I tried "Mosh (Dev") v0.5.5 (mosh 1.3.2) with the same setup as in the original post and the pixels are still being cut off:

![image](https://user-images.githubusercontent.com/4804/42787257-948b766a-890e-11e8-993e-08967693d33a.png)

**Comment by ryantm** [comment]
@rpwoodbu I just upgraded my computer (completely new computer, and new graphics card, etc.) and it is now running a later version of Windows:

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
```
and an older version of Mosh for Chrome `v0.4.5 (mosh 1.2.6)`
and almost certainly a more recent version of Chrome:
```
Google Chrome is up to date
Version 70.0.3538.77 (Official Build) (64-bit)
```
and the issue is gone!
