### ISSUE TITLE
Shutdown of chrome apps

### ISSUE THREAD

**Issue by Bartvelp** [rpwoodbu/mosh-chrome#191]
Hey, so this is not a issue report that has anything to do with mosh's code. 
But google has disabled the search feature for chrome apps and will completely disable them in the future.
Is there any way this can be ported to nodejs/electron? Or are there any good alternatives for windows mosh users?
[Article on this](https://arstechnica.com/gadgets/2017/12/google-shuts-down-the-apps-section-of-the-chrome-web-store/)

**Comment by rpwoodbu** [comment]
There is a [release](https://github.com/rpwoodbu/mosh-chrome/releases/tag/v0.4.5) of Mosh for Chrome that installs in Windows, using the NW.js framework.

Note that Chrome Apps are _not_ being removed for Chrome OS devices, at least not at this time. Mosh for Chrome was primarily created for Chrome OS, but it found a surprising audience in Windows users. 

As an aside, Chrome OS now has Linux app support (at least in the dev channel, and at least for some devices), which may obviate the utility of Mosh for Chrome for Chrome OS users. If I switch to using the official mosh on Chrome OS, this project is probably going to languish. Windows users, you've been warned.

**Comment by ironiridis** [comment]
New updates from the Chrome team seem to be indicating the ChromeOS support will be dropped in 2022. Desktop support may be gone by June.

**Comment by vapier** [comment]
@rpwoodb: can we set up a VC in like two weeks when I'm back in the US? I have some ideas here for the long term.

**Comment by ironiridis** [comment]
Did anything come of this? It seems like [some important commits](https://github.com/rpwoodbu/mosh-chrome/compare/v0.4.5...master) have landed that haven't seen a new release since 2017. Alternately: does it matter, with Windows WSL2 support?

**Comment by vapier** [comment]
it's in progress

keep in mind mosh-chrome is not Windows-specific

**Comment by vapier** [comment]
Please give the 0.37 release of Secure Shell a try:
https://chrome.google.com/webstore/detail/iodihamcpbpeioajjeobimgagajmlibd

I merged this project into it and should work on all platforms as it's an extension.  I've used it on Windows & CrOS and seems to work, albeit I've only tried IPv4.
