### ISSUE TITLE
[improvement] support openssh format privkey

### ISSUE THREAD

**Issue by kmahyyg** [rpwoodbu/mosh-chrome#199]
since ed25519 is much more recommended now, can this app support ed25519 algo. private key?
the default key of ed25519 is saved in openssh format instead of pem.

**Comment by ellbur** [comment]
As an alternative to adding support for OpenSSH format, the wiki page [Key-based-ssh-Authentication](https://github.com/rpwoodbu/mosh-chrome/wiki/Key-based-ssh-Authentication) could be updated to show how OpenSSH keys can be converted to PEM:

    ssh-keygen -p -f ~/.ssh/some_key_file -m PEM

(mosh-chrome currently does not warn/error if it cannot read the key format.)
