### ISSUE TITLE
Terminal escape sequences not working with Chrome 94.0.4606.61

### ISSUE THREAD

**Issue by ppetr** [rpwoodbu/mosh-chrome#216]
Since past day or two `mosh` Chrome extension (v.0.5.6, mosh 1.3.2) stopped working with any `ncurses` program such as `mc` or `vim`.  The screen is just blank after running such a program, or contains garbled fragments of the expected output.

The only thing that I'm aware of that has changed recently is Chrome being updated to [94.0.4606.61](https://chromereleases.googleblog.com/2021/09/stable-channel-update-for-desktop_24.html).

Resetting preferences to defaults didn't help.

Please let me know if there is anything I can do to help with debugging the issue.

**Comment by rpwoodbu** [comment]
I'm on Chrome 93, and am not having issues. Try using the Mosh functionality in the Secure Shell extension and see if it reproduces.

**Comment by ppetr** [comment]
Yes, when I run `mosh` from the Secure Shell extension (`v0.41 (mosh 1.3.2)`), it misbehaves exactly the same way. I tried reinstalling both extensions, but didn't help. Connecting natively through the Secure Shell extension, without `mosh`, works correctly.

**Comment by ppetr** [comment]
I just tried on another computer and `mosh` works both before (93.0.4577.82) and after (94.0.4606.61) upgrading Chrome. So apparently the issue is something else, unrelated to Chrome versions.

**Comment by ppetr** [comment]
I reinstalled Chrome and the issue went away. Hard to tell what was the cause.
