### ISSUE TITLE
Feature request: block/column selection

### ISSUE THREAD

**Issue by hrez** [rpwoodbu/mosh-chrome#222]
Feature request: block/column selection.

This is similar to putty block selection with ALT-left_button.

**Comment by rpwoodbu** [comment]
This would be an [hterm](https://chromium.googlesource.com/apps/libapps) feature, which is the terminal emulator used by Mosh for Chrome. If that feature is present in hterm, please reopen this issue and I will look into updating the hterm version used.

You might also try the mosh integration in [Secure Shell](https://chrome.google.com/webstore/detail/secure-shell/iodihamcpbpeioajjeobimgagajmlibd?hl=en) (based on this project), which should be using a recent hterm.
