### ISSUE TITLE
Text abuts edge of window

### ISSUE THREAD

**Issue by taralx** [rpwoodbu/mosh-chrome#49]
The white text abuts directly against the left/right edges of the window, resulting in an unpleasant juxtaposition of my text with the surrounding environment. Please add a pixel or two of padding. :)

**Comment by gsf** [comment]
Unfortunately, it isn't just a CSS change because of the way the divs are layered and the window is drawn. Below is the quick and dirty modification deep in hterm to get a pixel of padding. I have no idea how this would be exposed.

```diff
diff --git a/hterm/js/hterm_scrollport.js b/hterm/js/hterm_scrollport.js
index 67d0cf9..f58d326 100644
--- a/hterm/js/hterm_scrollport.js
+++ b/hterm/js/hterm_scrollport.js
@@ -735,10 +735,10 @@ hterm.ScrollPort.prototype.syncRowNodesDimensions_ = function() {
   }
 
   // Set the dimensions of the visible rows container.
-  this.rowNodes_.style.width = screenSize.width + 'px';
-  this.rowNodes_.style.height = visibleRowsHeight + topFoldOffset + 'px';
-  this.rowNodes_.style.left = this.screen_.offsetLeft + 'px';
-  this.rowNodes_.style.top = this.screen_.offsetTop - topFoldOffset + 'px';
+  this.rowNodes_.style.width = screenSize.width - 1 + 'px';
+  this.rowNodes_.style.height = visibleRowsHeight + topFoldOffset - 1 + 'px';
+  this.rowNodes_.style.left = this.screen_.offsetLeft + 1 + 'px';
+  this.rowNodes_.style.top = this.screen_.offsetTop - topFoldOffset + 1 + 'px';
 };
 
 hterm.ScrollPort.prototype.syncScrollHeight = function() {
```

**Comment by rpwoodbu** [comment]
Ah, good info, @gsf. That settles it, then: This should be in `hterm`, not in this project. They're pretty responsive to suggestions (and especially PRs), so if either of you want to bring it up with them, be my guest, and open a bug when they release a new hterm with the change so I can be sure to do a build against it.
