### ISSUE TITLE
Make urls clickable

### ISSUE THREAD

**Issue by pefoley2** [rpwoodbu/mosh-chrome#52]
e.g. clicking on http://google.com opens google.com in a new tab.

**Comment by T-101** [comment]
Sorry for the dupe. Anyhow, any progress on this since June 2014? :)

**Comment by rpwoodbu** [comment]
That issue is closed because this is an upstream issue with hterm. Check with hterm to see if any progress has been made. Feel free to reopen #117 if hterm commits a change which enables this, and I'll rebuild the app with the new hterm..
