### ISSUE TITLE
SSH RSA Key Login

### ISSUE THREAD

**Issue by seang96** [rpwoodbu/mosh-chrome#55]
I try logging in using my RSA key, however I get this:
Trying authentication type Public Key
Key auth failed: Access denied. Authentication that can continue: publickey,password

Using no passphrase, if i change it to have a passphrase, it still does not work. Thanks.

**Comment by scplay** [comment]
I can use  Rsa private key login in Putty successfully ,so I think my ssh config was right, But just copy id_rsa to mosh it fail ......................Hell Finally I get it. My User Name in Mosh was set wrong, I used to think that was just a nickname,But the UserName was the name that I want to login
