### ISSUE TITLE
Failure on loopback connections

### ISSUE THREAD

**Issue by Prize-Loser** [rpwoodbu/mosh-chrome#56]
When I connect via a loopback connection, mosh-chrome initiates a connection but never displays any data.  It's a 50/50 shot whether it stops responding after asking for my password or shows the blue bar and errors out after several seconds with the error:

mosh did not make a successful connection to [external IP]:60002.  Please verify that UDP port 60002 is not firewalled and can reach the server.

I've tested the same connection case with both mosh and JuiceSSH and have had no issues establishing or maintaining a stable connection, so it's not actually a firewall issue or an issue with the loopback connection itself.  mosh-chrome also has no issues when connecting to the local IP of the server instead of using the loopback.

**Comment by rpwoodbu** [comment]
Without more detail, I cannot proceed with this bug. Please reopen if you can answer these questions.
