### ISSUE TITLE
Please give option to run in a tab

### ISSUE THREAD

**Issue by davidn** [rpwoodbu/mosh-chrome#59]
At the moment mosh runs in it's own window. In some cases it would be preferable to run in a browser tab.  Could this feature be added? If it is possible by changing hterm options please add an example to the FAQ in the github wiki.

Thanks!

**Comment by jgallen23** [comment]
How does secure shell do it?

**Comment by rpwoodbu** [comment]
Secure Shell is not a Chrome Packaged App. It does not need UDPSocket.
