### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by niieani** [rpwoodbu/mosh-chrome#66]
Hi @rpwoodbu
First - great work on Mosh for Chrome so far!
I was wondering, since I've added mouse support to mosh about a year ago, if it would be possible to add these to the chrome version:
https://github.com/keithw/mosh/pull/461/files
I know the Chrome NaCL SSH client has mouse support, so it should be relatively easy to add.

**Comment by rpwoodbu** [comment]
This should work as of SHA 89ac2b2b8f4809335ca1a1700902d6142f55080e (update to upstream mosh 1.2.5). This should be going out to the dev channel this evening. Please mention on this issue if it does not work.
