### ISSUE TITLE
Update Hterm to add 24-bit color support

### ISSUE THREAD

**Issue by ysangkok** [rpwoodbu/mosh-chrome#68]
24-bit color support was added to Hterm: https://code.google.com/p/chromium/issues/detail?id=410371

Mosh-chrome doesn't seem to support 24-bit color yet. So I assume the version in mosh-chrome is too old.

Thank you.

**Comment by rpwoodbu** [comment]
Fixed in SHA 8f4b58d.

**Comment by agriffis** [comment]
Did this actually change anything? It seems to me that mosh would also need support for interpreting the 24-bit ANSI color escape sequences in order for this to actually work.

**Comment by rpwoodbu** [comment]
@agriffis Probably not. Check at http://mosh.mit.edu to see if they've added 24-bit color since the last release. They're working on a new major release now, which I hope to get into Mosh for Chrome soon after it is ready.

**Comment by agriffis** [comment]
I added https://github.com/keithw/mosh/issues/649
