### ISSUE TITLE
Function key doesn't work

### ISSUE THREAD

**Issue by soichih** [rpwoodbu/mosh-chrome#72]
Hi. I am using mosh on Chromebox with a standard USB keyboard. Chromebox/book captures function key events internally so if I press F1/F2, etc.. (say I am using byobu terminal multiplexer) mosh doesn't even know that I am pressing them.

This could be a Chromebox/book specific issue, but is there anyway to configure mosh so that all function key input to mosh-chrome will be passed to my ssh server?

**Comment by rpwoodbu** [comment]
If you hold down the search key while pressing the function keys, they will be interpreted literally by Chrome OS, and thus by Mosh.

You may have to setup the caps lock key to be a search key. I can't remember if I had to do this or not on my Chromebox with standard keyboard. Also, in the same place, you can actually tell Chrome OS to treat the function keys literally if you prefer (and as a Byobu user, you very well may).

chrome://settings-frame/keyboard-overlay
