### ISSUE TITLE
Can't resize mosh window by holding Right-Top corner of the window

### ISSUE THREAD

**Issue by soichih** [rpwoodbu/mosh-chrome#73]
On Windows 8.1, I can't resize the mosh terminal window by dragging / dropping the right-top corner of the window. All other corner works, however. I am not sure if this is just some quirk with Chrome itself, but reporting this here just in case this was fixable through mosh-chrome.

**Comment by rpwoodbu** [comment]
Can you reproduce this with another Chrome Packaged App or one where you've set it to open in a window instead of a tab?

**Comment by soichih** [comment]
I tried couple of other Chrome Apps but so far they all run as browser tab. Do you know of an app that works like mosh-chrome?

**Comment by rpwoodbu** [comment]
[CIRC](https://chrome.google.com/webstore/detail/bebigdkelppomhhjaaianniiifjbgocn?utm_source=chrome-app-launcher-info-dialog) runs in a window as a Packaged App, and seems to use the default window trimmings. Give that a shot.

**Comment by jpwoodbu** [comment]
I might have reproduced the behavior you're describing. I can move the mouse cursor over top of the _close_ button for the window and the mouse cursor will change to indicate that the window can be resized, but trying to resize from this position fails. If I carefully move the mouse cursor over to the space between the _close_ button and the edge of the window, I can successfully resize the window.

In contract, when using notepad.exe, the mouse cursor does not change to indicate a window resize action when mousing over the _close_ button.

**Comment by jpwoodbu** [comment]
I tried the same actions with another packaged app, [CIRC](https://chrome.google.com/webstore/detail/circ/bebigdkelppomhhjaaianniiifjbgocn?hl=en-US&utm_source=chrome-ntp-launcher) and it behaves the same way. I don't think this behavior is mosh-chrome specific.

**Comment by rpwoodbu** [comment]
Thanks, @jpwoodbu, for verifying that. I am closing this bug, as there's nothing I can do. Anyone particularly interested in this issue should open a bug with the Chromium project.
