### ISSUE TITLE
Feature Request: Make pasting mouse button configurable

### ISSUE THREAD

**Issue by soichih** [rpwoodbu/mosh-chrome#74]
Hello.

I am used to pasting copied (selected) text by right clicking on a terminal window (like on Putty). Is there anyway you could make the mouse button for pasting configurable?

**Comment by rpwoodbu** [comment]
This is purely an hterm thing, which is the terminal emulator used by Mosh for Chrome. You should bring it up with them. See the [FAQ](https://github.com/rpwoodbu/mosh-chrome/wiki/FAQ) for details on how to adjust items related to the terminal.
