### ISSUE TITLE
Window title

### ISSUE THREAD

**Issue by gsf** [rpwoodbu/mosh-chrome#80]
One thing I like in hterm is that I can set my window title to `user@host etc.` via the usual escape sequences. I have no idea how hard it would be to support that feature here as well.

**Comment by rpwoodbu** [comment]
This functionality already exists, because Mosh for Chrome uses hterm. Let me know if it isn't working for you.

**Comment by gsf** [comment]
Strange, it isn't working for me. Is there an option I need to tweak? No amount of escape sequence echoing or PS1 setting appears to modify the title bar. Here are windows for mosh-chrome and chrome secure shell with both at default settings:

![titlebar-mosh](https://cloud.githubusercontent.com/assets/151913/6555805/26e24c46-c63f-11e4-94f0-ce9553564ab6.png)

![titlebar-secure-shell](https://cloud.githubusercontent.com/assets/151913/6555812/2c52865a-c63f-11e4-9116-c074d3a13c37.png)

**Comment by rpwoodbu** [comment]
Interesting. Is that Windows? I get a title bar in Unity on Ubuntu Linux. And I sorta get titles in Chrome OS (they don't show on the window for some reason, but they show when you have more than one window open and you click on the app icon on the panel). This works for both Mosh for Chrome and Secure Shell.

The fact that I don't get a title in Chrome OS makes me wonder if Chrome is allergic to title bars. It is worth noting that Secure Shell is an old-school app, where as Mosh for Chrome is (necessarily) a Packaged App, so the behavior could be slightly different.

**Comment by gsf** [comment]
Yes those screenshots were in Windows 8.1. And I see the same thing you see on my Chromebook -- no window title in either Mosh or Secure Shell. I now remember preferring the Crosh Window on the Chromebook because it displays titles on the window when Secure Shell doesn't.

**Comment by rpwoodbu** [comment]
This seems to be a larger Chrome Packaged Apps issue:
https://code.google.com/p/chromium/issues/detail?id=225773

The only thing I could do is put Mosh for Chrome in a frameless window and provide my own title bar. There may even be some other benefits to doing so as part of a larger UI refresh. But don't expect such extravagances anytime soon.

**Comment by gsf** [comment]
I was just about to link to the same issue. Best to wait for the Chromium team to resolve that. Thanks for looking into it!
