### ISSUE TITLE
Paste doesn't work while running under Windows

### ISSUE THREAD

**Issue by goekesmi** [rpwoodbu/mosh-chrome#84]
I'm using mosh-chrome as a chrome app under Chrome stable on Windows 8.1 Pro.

Paste doesn't work at all.   Neither from selections copied from putty, or from selections made from the same mosh window.

How do I provide useful diagnostics/debugging data to work with?

**Comment by rpwoodbu** [comment]
How are you trying to paste? On Linux and Chrome OS, you use `Ctrl-Shift-V`. Maybe an FAQ entry is in order.

**Comment by goekesmi** [comment]
Right click, which is working for me on ChromeOS.  I'll test your
suggestion today.  Yes, an FAQ may be in order.

**Comment by rpwoodbu** [comment]
Neat, right-click also works! Interesting that it isn't mentioned in the Secure Shell [FAQ](http://git.chromium.org/gitweb/?p=chromiumos/platform/assets.git;a=blob;f=chromeapps/nassh/doc/faq.txt).

Once you determine if `Ctrl-Shift-V` works for you, I'll add a FAQ entry.

**Comment by goekesmi** [comment]
Right click matches what I use on ChromeOS's SSH client.  thus, I was using
what matched there, and was suprised when it didn't work on Windows.

On a hunch, I just went and tested ssh as a chrome app on windows.  Right
click doesn't work for paste there either.  I'm suspecting this is
something with hterm.

Ctl-Shift-V works on both, however.

I now have a work around.  An FAQ entry would be good.  And I suspect
there's more digging to be done.

**Comment by rpwoodbu** [comment]
OK, thanks for the sleuthing. I decided to add this to the main documentation, as copy/paste is pretty fundamental. I agree that the right-click issue sounds like an `hterm` thing, so I'll leave it to them.
