### ISSUE TITLE
Fullscreen exited when ESC pressed

### ISSUE THREAD

**Issue by gsf** [rpwoodbu/mosh-chrome#85]
Unfortunately, apps need to do a little dance to stay in fullscreen mode on the chromebook when ESC is pressed. See https://developer.chrome.com/apps/app_window#property-AppWindow-fullscreen.

**Comment by rpwoodbu** [comment]
Ah, thanks for that tidbit. I've been burnt by this before. I wondered if `hterm` ought to implement this, but then I realized that Secure Shell doesn't seem to have this problem. And I'm not finding `overrideEsc` anywhere in `hterm` or `nassh`. Huh.

Nonetheless, this should be easy enough to do, so I'll look into it.

**Comment by gsf** [comment]
Yes I think this is another caveat that only applies to new-style apps.
