### ISSUE TITLE
Tab keypress lost, causes TypeError in hterm

### ISSUE THREAD

**Issue by gsf** [rpwoodbu/mosh-chrome#88]
This is on the dev channel of ChromeOS, and it's really an hterm issue, and it's a known issue (https://code.google.com/p/chromium/issues/detail?id=468560), but I thought I'd create an issue here in case anyone else runs into it while using mosh-chrome. 

The error is caused by the attempt to assign `false` to e.shiftKey at line 1199 of hterm.js (line 161 of hterm_keyboard_keymap.js). A workaround for the time being is to simply remove that line.

**Comment by gsf** [comment]
And from that chromium issue thread it appears that it's fixed in hterm as of this commit: https://chromium-review.googlesource.com/#/c/261315.

**Comment by gsf** [comment]
Looks from that issue thread like the fix has been rolled into stable secure shell so as soon as mosh-chrome updates that dependency we should be good.

**Comment by sasnfbi1234** [comment]
about how long do you think that will take?

**Comment by rpwoodbu** [comment]
Gadzooks! I just updated myself, and am now hit with this. Looks like I'll be fixing this immediately. Stay tuned.

**Comment by sasnfbi1234** [comment]
thanks a million rpwoodbu!

**Comment by sasnfbi1234** [comment]
so sorry. how could I update to fix this issue?

**Comment by rpwoodbu** [comment]
I have just pushed this to the "dev" channel. I will push to the main app shortly. It will update itself.

**Comment by sasnfbi1234** [comment]
open source software is so cool! thanks

**Comment by rpwoodbu** [comment]
For any onlookers: Be sure to close your Mosh windows for a few minutes for Chrome to apply the update.

**Comment by gsf** [comment]
Thanks for the update, @rpwoodbu!
