### ISSUE TITLE
Update killed NaCl

### ISSUE THREAD

**Issue by telmacblack** [rpwoodbu/mosh-chrome#95]
The update since maybe two weeks ago has broken NaCl. Mosh starts, it prints the "new NaCl driver" thing, and then sits there. I was running on regular (non-dev) mosh but that now says incompatible in the store (I tried removing it and reinstalling). Dev is broken as well.

Running chrome os Version 41.0.2272.102 64-bit on a lenovo x131e

**Comment by rpwoodbu** [comment]
This is a dup of Issue #94. Old versions of Chrome are not supported. Please update to the latest stable release.
