### ISSUE TITLE
Improve "resolution failed -110" error message

### ISSUE THREAD

**Issue by CryptoX** [rpwoodbu/mosh-chrome#96]
Mosh v. 0.2.12.91

I can Mosh from linux box to another box but NaCle version crashes with this error "resolution failed -110"

**Comment by rpwoodbu** [comment]
I need to improve that error message. That simply means the name could not be resolved to an IPv4 address. Be sure that the name is spelled correctly, and is fully specified.

I'm keeping this bug open to make the error message more meaningful, as you're not the first to hit this.

**Comment by CryptoX** [comment]
Thanks, I have resolved the problem, misspelling was the problem indeed. An error message like "Your host is not reachable , please check your hosname/user name" might be better than current error message.
