### ISSUE TITLE
Can't use C--

### ISSUE THREAD

**Issue by yacoob** [rpwoodbu/mosh-chrome#97]
Looks like Mosh's terminal is intercepting C-- and C-+ for font size adjustment. Is there a way to decouple those, and have those sent to the remote terminal? I'm using C-- as tmux prefix. :)

**Comment by rpwoodbu** [comment]
This would be a function of the underlying `hterm`. See the [Mosh for Chrome FAQ](https://github.com/rpwoodbu/mosh-chrome/wiki/FAQ) about how to fiddle with the terminal behavior. I did look briefly at the `hterm` FAQ (linked from the aforementioned FAQ), and there's some discussion about the zoom behavior.

**Comment by cgull** [comment]
Ctrl-Shift-dash works for me on a stock configuration, at least on OS X.
