### ISSUE TITLE
"mosh: sendto: I/O error" in current Mosh (dev)

### ISSUE THREAD

**Issue by geofft** [rpwoodbu/mosh-chrome#98]
On current Chrome stable (44.0.2403.107) for Windows 8.1, the dev version of Mosh on the web store (version 0.2.12.137) can't send any UDP traffic. The overlay bar displays "mosh: sendto: I/O error" and then gives up after a bit without making contact.

The regular version of the Mosh app (0.2.12.91) works fine.

This started happening after I rebooted my computer. I had a pending Chrome update, but I don't see anything relevant in the changelog, so I'd vaguely guess that I just got a new dev version with the new upstream Mosh release, which broke things.

**Comment by cgull** [comment]
More info (from IRC conversation):

This also happens to me on OS X, Version 44.0.2403.107 (64-bit)
So, not just a Windows thing.

It fails to a host with IPv4, but IPv6 to the same host works fine.

**Comment by rpwoodbu** [comment]
Is this 100% repeatable? Does it happen for some hosts and not others? I've only tested on Chrome OS and Linux, so maybe I need to do a bit more testing.

**Comment by cgull** [comment]
I just tried this on an Win8.1 VM and a completely different set of hosts (IPv4 only).  mosh-dev fails and mosh works.

**Comment by rpwoodbu** [comment]
Thanks for the sleuthing. I will try to repro this evening. Did you happen to look in the JS console to see if there were any log messages?

**Comment by rpwoodbu** [comment]
From the JS console on a Windows machine (h/t @jpwoodbu):

    NativeUDP::Send(): socket_->SendTo() failed with -2

Interesting. Digging in now.

**Comment by rpwoodbu** [comment]
-2 is the Pepper API error [PP_ERROR_FAILED](https://developer.chrome.com/native-client/pepper_dev/c/group___enums.html#gga06fc87d81c62e9abb8790b6e5713c55ba06a8964482e41bf50c45c0d9dd281830). Quote from the docs:

> PP_ERROR_FAILED
> This value indicates failure for unspecified reasons.

Well, that's helpful. :-/  The digging continues.

**Comment by rpwoodbu** [comment]
Thanks to all who are running the dev track and contributed to this bug (especially @geofft for the initial report). This is exactly why I created a dev track. A new build is rolling out to dev now.

**Comment by geofft** [comment]
I can confirm that 0.2.12.142 fixes the problem. Thanks for the quick response!
